### ISSUE TITLE
USER STORY: Events Page

### ISSUE THREAD

**Issue by JoeYip13** [JoeYip13/project-5-drf-api-react#35]
As a **registered user** I can **view all the upcoming events, ordered by closest dates first** so that **I can discover and access information about upcoming events**

## Acceptance Criteria

1. Acceptance Criteria 1: Have a dedicated events page section on the platforms main navigation
2. Acceptance Criteria 2: Main events page displays a visually appealing and intuitive layout
3. Acceptance Criteria 3: Events are listed with key details such as event name, event date, time, and location. 

## Tasks
- [ ] Design the layout and appearance of the events page, focusing on user-friendly navigation and visual appeal.
- [ ] Create a new model in Django to represent event related posts.
- [ ] Develop frontend components to list event posts with titles, dates, time and location.
- [ ] Conduct user testing to ensure the Events page meets user expectations and is easy to navigate.
- [ ] Deploy the updated website with the Events page to the production environment for user access.
