### ISSUE TITLE
USER STORY: Create a Event

### ISSUE THREAD

**Issue by JoeYip13** [JoeYip13/project-5-drf-api-react#36]
As a **registered user** I can **create and publish an event** so that **I can efficiently promote and manage gatherings for participants**

## Acceptance Criteria

1. Acceptance Criteria 1: There is a clear and user-friendly event creation form accessible from the events page
2. Acceptance Criteria 2: The form includes fields for event name, event date, time, location, description.
3. Acceptance Criteria 3: I can add images or banners for promotional purposes.

## Tasks
- [ ] Design the event creation form, ensuring a logical and intuitive layout.
- [ ] Implement the event creation form, including validation for mandatory fields.
- [ ] Conduct user testing to ensure the form meets user expectations and is easy to submit.
- [ ] Deploy the updated website with the Event form page to the production environment for user access.
