### ISSUE TITLE
USER STORY: Edit an Event

### ISSUE THREAD

**Issue by JoeYip13** [JoeYip13/project-5-drf-api-react#38]
As a **registered user** I can **edit an event details** so that **I can keep participants informed about any changes or updates to the event.**

## Acceptance Criteria

1. There is a clear and easily accessible option to edit an event from the organizer's dashboard.
2. Clicking the edit option opens a user-friendly form with pre-populated fields containing the current event details.
3. Organizers can modify event details such as name, date, time, location, description, schedule, and other relevant information.

## Tasks
- [ ] Design the event editing option, ensuring it is easily noticeable and logically placed on the events page.
- [ ] Create a user-friendly event editing form with a clear layout.
- [ ] Conduct user testing to ensure the form meets user expectations and is easy to submit.
- [ ] Deploy the updated website with the Event form page to the production environment for user access.
